-- Classroom Hub — Supabase schema
-- Run once: Supabase dashboard -> your project -> SQL Editor -> New query -> paste all of this -> Run

create table if not exists announcements (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  author text not null default 'Teacher',
  created_at timestamptz not null default now()
);

create table if not exists resources (
  id bigint generated by default as identity primary key,
  subject text not null,
  topic text not null,
  name text not null,
  type text,
  url text not null,
  public_id text,
  created_at timestamptz not null default now()
);
create index if not exists resources_subject_idx on resources (subject);

create table if not exists messages (
  id bigint generated by default as identity primary key,
  name text not null,
  status text not null,
  class text,
  contact text not null,
  message text not null,
  created_at timestamptz not null default now()
);

-- Lock all three down completely — deliberately no policies below.
-- The Flask backend connects with the SERVICE ROLE key (see database.py),
-- which bypasses RLS by design. With RLS on and zero policies, nothing else
-- -- not the anon key, not a leaked URL -- can read or write these tables
-- directly through Supabase's API. Every access check happens in exactly
-- one place: the Flask app's own @require_admin routes.
alter table announcements enable row level security;
alter table resources enable row level security;
alter table messages enable row level security;
